### PR TITLE
fix: Ensure paired server warning is removed

### LINKED ISSUE #45: theme picker server error stays even after it ends up loading successfully
image

In my screenshot you can see that the error is present but the picker is working. I think there was a brief moment during app launch where it was unable to load the picker, but after it started working the error stayed, I would expect it to be cleaned up upon the picker loading successfully.

### PR DESCRIPTION
**Pull request by gadenbuie**
Fixes #45

With the current approach, if the app takes a while to start up the warning message isn't removed and sticks around forever.

To reproduce the issue in #45, add `time.sleep(2)` at the start of the server function of `examples/theme-picker/app.py`.

### CODE REVIEW

File: shinyswatch/picker/theme_picker.js [hunk 1]
```diff
@@ -211,13 +211,30 @@
...
+      warning.style.display = 'block'
+    }
+  }
+
+  let displayWarning
+  if (typeof window.Shiny.setInputValue === "function") {
+    displayWarning = setTimeout(showWarning, 1000)
+  } else {
+    $(window).one("shiny:idle", showWarning)
+  }
```
[the remark this answers is not in the document]
Comment (schloerke) [reply shinyswatch/picker/theme_picker.js:233]: We can now use https://github.com/rstudio/shiny/blob/34f9e4484d88c7f8547053a2da9ab312cec50bc8/NEWS.md#L25 !

```suggestion
  Shiny.initializedPromise.then(function() {
    $(window).one("shiny:idle", showWarning)
  });
```

We'd need a min py-shiny version of 1.1.0. via https://github.com/posit-dev/py-shiny/pull/1617

File: shinyswatch/picker/theme_picker.js [hunk 2]
```diff
@@ -211,13 +211,30 @@
...
 
   Shiny.addCustomMessageHandler('shinyswatch-hide-warning', function (_) {
-    window.clearTimeout(displayWarning)
+    if (displayWarning) window.clearTimeout(displayWarning)
```
Comment (schloerke) [inline shinyswatch/picker/theme_picker.js:236]:
```suggestion
```

File: shinyswatch/picker/theme_picker.js [hunk 3]
```diff
@@ -211,13 +211,30 @@
...
+  }
+
+  function showWarning() {
+    const warning = document.getElementById('shinyswatch_picker_warning')
+    if (warning) {
+      warning.style.display = 'block'
+    }
+  }
+
+  let displayWarning
```
Comment (schloerke) [inline shinyswatch/picker/theme_picker.js:228]:
```suggestion
```

File: shinyswatch/picker/theme_picker.js (hunk 1 above)
[the remark this answers is not in the document]
Comment (gadenbuie) [reply shinyswatch/picker/theme_picker.js:233]: Yeah that's cool and I thought about doing this but I don't think it's necessary

File: shinyswatch/picker/theme_picker.js [hunk 4]
```diff
@@ -225,7 +225,11 @@
     }
   }
 
-  $(window).one("shiny:idle", showWarning)
+  if (typeof window.Shiny.setInputValue === "function") {
+    setTimeout(showWarning, 1000)
```
Comment (gadenbuie) [inline shinyswatch/picker/theme_picker.js:229]: Turns out we need this case if the theme picker is added via dynamic UI but the server isn't registered

**Comment by gadenbuie** [comment]
I also made the warning message an actual Bootstrap alert
image

File: shinyswatch/picker/theme_picker.js (hunk 4 above)
Comment (schloerke) [reply shinyswatch/picker/theme_picker.js:229]: Thank you!
